### ISSUE TITLE
Please update dist/ZeroBundle-win.zip

### ISSUE THREAD

**Issue by l5h5t7** [HelloZeroNet/ZeroBundle#11]
Some days ago, @rexdf committed https://github.com/HelloZeroNet/ZeroBundle/pull/10/commits/d97e3ecc5f884fb62c2d71ffcbbead0ac0907897 , but now dist/ZeroBundle-win.zip is still not updated, so new users download the old ZeroBundle-win.zip so they can't run as Administrator.

**Comment by HelloZeroNet** [comment]
Thanks for the notification, updated: https://github.com/HelloZeroNet/ZeroBundle/commit/d124190d1041d82df441e068f3b6ee0e4c3d922d
