### ISSUE TITLE
Visual C++ Redistributable Packages 2013 is required on Windows after update OpenSSL

### ISSUE THREAD

**Issue by l5h5t7** [HelloZeroNet/ZeroBundle#16]
Please update Visual C++ Redistributable Packages in ZeroBundle.

**Comment by HelloZeroNet** [comment]
The zerobundle package updating is not nolved yet, so we have to re-compile openssl for older packages or find a binary

**Comment by HelloZeroNet** [comment]
Fixed by switching to this version:
https://indy.fulgan.com/SSL/openssl-1.0.2k-i386-win32.zip
