### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by TheNain38** [HelloZeroNet/ZeroBundle#5]
And if you do so, update the download link in the ZeroBundle Readme.md and also In the ZeroNet Readme.md

**Comment by HelloZeroNet** [comment]
Why? Nothing changed since 0.1.1

**Comment by TheNain38** [comment]
You have merge my pull request

**Comment by HelloZeroNet** [comment]
New release is only necessary on mayor changes

**Comment by TheNain38** [comment]
Ok

**Comment by TheNain38** [comment]
@HelloZeroNet Could you add the latest lib https://github.com/jgarzik/python-bitcoinrpc/tree/master/bitcoinrpc to the ZeroBundle

**Comment by HelloZeroNet** [comment]
I think it's not necessary, if someone wants to use the plugin will install it

**Comment by TheNain38** [comment]
Yes, but it needs the latest, not the pip one

**Comment by HelloZeroNet** [comment]
you can add it to plugin's directory like maxminddb in sidebar

**Comment by TheNain38** [comment]
Yes, but users wanting to use Zeroname-local will not understand why it doesn't work if they enable it

**Comment by HelloZeroNet** [comment]
if you add it to the plugins directory then it should work
