### ISSUE TITLE
Signed downloads

### ISSUE THREAD

**Issue by HulaHoopWhonix** [HelloZeroNet/ZeroBundle#8]
Hi I wanted to document ZeroNet installation for our users but the lack of signed downloads was discouraging. Can you please provide signed tarballs and also include these in your download page instructions?

**Comment by MuxZeroNet** [comment]
Do you mean `gpg2 --armor --clearsign SHA256SUM`? :smiley:

**Comment by HulaHoopWhonix** [comment]
Hi this is a very old ticket I believe you've since completed it. IIRC you started signing your binaries with 4096 bit keys lately. We are working on integrating ZeroNet into out privacy distro WhonixOS instead of just documenting how to download, verify, install ...

cc/ @adrelanos

**Comment by HelloZeroNet** [comment]
Nice, thanks!
